### ISSUE TITLE
babel aliases

### ISSUE THREAD

**Issue by headfire94** [SyMind/rspackify#3]
Webpack uses babel-loader which has aliases specified in babel.config or .babelrc. 
like:
```
[
      'module-resolver',
      {
        alias: alias,
      },
    ],
```

Rspack requires aliases to be defined in config itself.
Need to check if babel-loader exist and copy aliases from it

**Comment by headfire94** [comment]
see https://github.com/headfire94/rspackify/pull/1

**Comment by SyMind** [comment]
@headfire94 Thank you very much for pointing out the issue. I will address it in due course.
